# Generated by Django 5.0.2 on 2024-04-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='pub_date_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='pub_date_post',
        ),
    ]
