# Generated by Django 5.0.2 on 2024-05-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment_comment_owner_post_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_owner',
        ),
    ]
