# Generated by Django 5.0.4 on 2024-04-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='tag',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
