# Generated by Django 5.0.2 on 2024-05-08 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=100)),
                ('text', models.TextField(default='', max_length=100)),
                ('answer1', models.CharField(default='', max_length=100)),
                ('answer2', models.CharField(default='', max_length=100)),
                ('answer3', models.CharField(default='', max_length=100)),
                ('answer4', models.CharField(default='', max_length=100)),
                ('correct_answer', models.IntegerField(choices=[(0, 'Answer 1'), (1, 'Answer 2'), (2, 'Answer 3'), (3, 'Answer 4')], default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=20, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=True)),
                ('host', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='game.quiz')),
            ],
        ),
    ]
