# Generated by Django 5.0.2 on 2024-05-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_participants_alter_room_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
