# Generated by Django 5.0.2 on 2024-04-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_room_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'rooms'},
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
