# Generated by Django 5.0.2 on 2024-04-16 01:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_room_options_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='room_code', unique=True),
        ),
    ]
