# Generated by Django 5.0.2 on 2024-04-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_room_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
