# Generated by Django 5.0.2 on 2024-04-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_room_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
