# Generated by Django 5.0.2 on 2024-04-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_quiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.question')),
            ],
        ),
    ]
