# Generated by Django 5.0.2 on 2024-04-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_question_answer1_remove_question_answer2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
