# Generated by Django 5.0.2 on 2024-04-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_quiz_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
