# Generated by Django 5.0.2 on 2024-04-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_quiz_created_time_remove_quiz_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='answer1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, 'Answer 1'), (2, 'Answer 2'), (3, 'Answer 3'), (4, 'Answer 4')], default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
