# Generated by Django 5.0.2 on 2024-04-17 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_question_description_question_answer1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeanerInRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='game.room')),
            ],
        ),
    ]
