# Generated by Django 5.0.2 on 2024-04-23 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_question_quiz_alter_room_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.quiz'),
        ),
        migrations.AlterField(
            model_name='room',
            name='quiz',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='game.quiz'),
        ),
    ]
