# Generated by Django 5.0.2 on 2024-04-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_room_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
