# Generated by Django 5.0.2 on 2024-04-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_alter_room_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(choices=[(models.CharField(default='', max_length=100), 'Answer 1'), (models.CharField(default='', max_length=100), 'Answer 2'), (models.CharField(default='', max_length=100), 'Answer 3'), (models.CharField(default='', max_length=100), 'Answer 4')], default=1),
        ),
    ]
