# Generated by Django 5.0.2 on 2024-04-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, models.CharField(default='', max_length=100)), (2, models.CharField(default='', max_length=100)), (3, models.CharField(default='', max_length=100)), (4, models.CharField(default='', max_length=100))], default=1),
        ),
    ]
