# Generated by Django 5.0.2 on 2024-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(choices=[('A', models.CharField(default='', max_length=100)), ('B', models.CharField(default='', max_length=100)), ('C', models.CharField(default='', max_length=100)), ('D', models.CharField(default='', max_length=100))], default='A'),
        ),
    ]
